- src/Graphics/Shader.h
- src/Graphics/Texture.h
- src/LH3D/LHOSFile.cpp
- src/LH3D/LHOSFile.h
- src/LH3D/LandIsland.cpp
- src/LH3D/oldLH3DIsland.cpp
- src/LH3D/oldLH3DIsland.h
- src/main.cpp
- LHOS File functions
Added missing file functions for POSIX.
- Includes for C/C++std functions
Added missing includes for C/C++std functions so that gcc can build the project.
> Make it build on Linux

- src/3D/LandBlock.h
- src/3D/LandIsland.h
- src/3D/MeshPack.cpp
- src/3D/MeshPack.h
- src/3D/oldLH3DIsland.cpp
- src/AllMeshes.h
- src/Common/OSFile.cpp
- src/Common/OSFile.h
- src/Game.cpp
- src/Graphics/Mesh.cpp
- src/Graphics/VertexBuffer.cpp
Hi @handsomematt,
I see you've done some work on openblack.
Trying to build it on Linux gave me a couple of warnings and errors.
Here is a pull request where each commit is related to one of those problems, and I hope those shouldn't break anything on non-linux platforms.
I can split the PR if there are some changes you don't want to apply.
> Suggested patch

- CMakeLists.txt
Allow the user to set the C++ standard to allow to use even newer
standards
> allow user to define the CXX_STANDARD

- src/Common/File.cpp
- src/Common/File.h
- src/Common/FileSystem.cpp
- src/Common/FileSystem.h
The one that ships with ubuntu 18.04 by default
> Add support for GCC7's experimental filesystem

- CMakeLists.txt
- cmake/Hunter/config.cmake
ref: https://github.com/openblack/openblack/issues/44
> hunter: disable building of glm tests

- appveyor.yml
I can't seem to get it to work, not even with Visual Studio 15 2017 image, dropping it
> ci: appveyor: disable mingw build

- appveyor.yml
enable cache, also includes https://github.com/openblack/openblack/pull/55
> Ci appveyor cache

- .travis.yml
- ci/travis.fedora.sh
- ci/travis.ubuntu.sh
Images on docker hub are still going through (hopefully final) build and this is what's needed here to make use of them.
I will retrigger the CI tomorrow, once the images are all done.
Fixes #66
> Update travis to use new docker images

- src/Game.cpp
- src/Game.h
- src/Gui.cpp
- src/Gui.h
- src/LHVMViewer.cpp
- src/LHVMViewer.h
- src/MeshViewer.cpp
- src/Renderer.cpp
- src/Renderer.h
The main two things added here are a GUI class with ability for multiple imgui contexts to co-exit.
Second is the Game Config struct which will help add and remove future options without having to make individual accessors.
The GUI class can be extended for custom imgui implementation (i.e. bgfx or other renderers).
> Add Gui Class

- src/Entities/Components/Model.h
- src/Entities/Registry.cpp
- src/LHScriptX/FeatureScriptCommands.cpp
> Implement tree spawns for land 1

- .gitignore
- CMakeLists.txt
- src/3D/L3DSubMesh.cpp
- src/Game.cpp
- src/GameWindow.cpp
- src/GameWindow.h
- src/Graphics/DebugLines.cpp
- src/Graphics/DebugLines.h
- src/Graphics/VertexBuffer.cpp
- src/Graphics/VertexBuffer.h
- src/Gui.cpp
- src/Gui.h
Small changes done while preparing for bgfx.
Small changes to gitignore and cmake.
Fixed an sdl bug
Removed some dead code.
Improve readability of Gui class and prepare it for bgfx-imgui.
> Rendering refact

- src/3D/LandBlock.cpp
- src/3D/Water.cpp
- src/Graphics/DebugLines.cpp
- src/Graphics/DebugLines.h
- src/Graphics/Mesh.cpp
- src/Graphics/Mesh.h
- src/Graphics/VertexBuffer.cpp
- src/Graphics/VertexBuffer.h
Simplify Debug Draw by using existing code in Mesh
> Mesh simplify

- src/3D/L3DSubMesh.cpp
- src/3D/LandIsland.cpp
- src/3D/Sky.cpp
- src/3D/Water.cpp
- src/Graphics/ShaderProgram.cpp
- src/Graphics/ShaderProgram.h
Merge set uniform and texture into a set sampler function.
Let the program bind the texture from the set texture sampler.
> Graphics: Add Explicit Texture Sampler setting

- CMakeLists.txt
- src/CMakeLists.txt
shaders weren't copied. The GLOB expression searched in `openblack/src/assets` instead of `openblack/assets`
> fix copy of shader from assets to binary dir

- src/Game.cpp
- src/Renderer.cpp
- src/Renderer.h
This changes makes it possible to start openblack from any working
directory. No need to cd to build/bin/ to execute openblack anymore!
> load shaders relative to openblack binary

- .gitmodules
- CMakeLists.txt
- appveyor.yml
- ci/Dockerfile.ubuntu.template
- ci/travis.ubuntu.sh
- cmake/backport/FetchContent.cmake
- cmake/backport/FetchContent/CMakeLists.cmake.in
- external/imgui/CMakeLists.txt
- src/3D/Water.cpp
- src/Gui.cpp
- src/LHVMViewer.cpp
- src/LHVMViewer.h
- src/MeshViewer.cpp
Follows #116
cmake: Use FetchContent instead of submodules
Update minimum cmake to 3.14
Remove all submodules.
Fetch content fetches dependencies at cmake config time and puts them in
the cmake build directory.
> cmake: Use FetchContent instead of submodules

- src/Game.cpp
Fix valgrind warning about condition based on uninitalized variable
> game: Initialize interestion

- src/Entities/Components/Stream.h
Make  immutable.
Remove sorting and replace with finding min which is
the actual goal of this bit of code
> Fix crash during stream creation

- src/MeshViewer.cpp
- src/MeshViewer.h
> meshviewer: add filter to selections

- src/3D/L3DSubMesh.cpp
Missing fix that wasn't included in #136
> L3DSubMesh: Final fix for s_diffuse error

- src/Common/FileSystem.cpp
- src/Common/FileSystem.h
- src/Game.cpp
- src/Gui.cpp
- src/LHScriptX/FeatureScriptCommands.cpp
Add function to fix path based on known false paths.
Remove explicit path loading from code.
> script: Load land from script

- CMakeLists.txt
- appveyor.yml
- ci/travis.fedora.sh
- ci/travis.ubuntu.sh
This should significantly speed-up the bgfx build
> ci: Use system deps for spirv tools

- assets/shaders/fs_water.sc
- assets/shaders/varying.def.sc
- assets/shaders/vs_water.sc
- src/3D/Water.cpp
- src/3D/Water.h
Mixing diffuse + reflection doesn't give us an ideal result, we'll want to mess around with different blending methods.
> Add diffuse texture to Water, mix with reflection buffer.

- src/3D/Camera.cpp
Changes one `-=` to `+=` for code readability and consistency.
> Make camera input velocity change consistent

- apps/l3dtool/l3dtool.cpp
- apps/lndtool/lndtool.cpp
- components/g3d/include/g3d_file.h
- components/l3d/include/l3d_file.h
- components/l3d/src/l3d_file.cpp
- components/lnd/include/lnd_file.h
- components/lnd/src/lnd_file.cpp
- src/3D/L3DMesh.cpp
- src/3D/L3DMesh.h
- src/3D/L3DSubMesh.cpp
- src/3D/L3DSubMesh.h
- src/3D/LandIsland.cpp
- src/3D/Sky.cpp
- src/Game.cpp
- src/Game.h
- src/Graphics/ShaderProgram.cpp
- src/Gui.cpp
- src/Gui.h
- src/Renderer.cpp
- src/Renderer.h
- src/main.cpp
#151 is kind of stalled due to ci and vcpkg's bad assimp package.
I don't want that to block these good changes so I extracted the non assimp pre commits
> Prep for running openblack with mock data and null renderer

- azure-pipelines/templates/publish.yml
Append git commit id to artifact to have record of which version it comes from
> ci: Add version to artifact name

- apps/l3dtool/l3dtool.cpp
- apps/lndtool/lndtool.cpp
- components/l3d/src/l3d_file.cpp
- components/lnd/include/lnd_file.h
- src/3D/LandBlock.cpp
- src/3D/LandIsland.cpp
- src/Common/Bitmap16B.cpp
- src/Common/FileStream.cpp
- src/LHScriptX/Lexer.h
- src/Renderer.cpp
In an attempt to fix some of the errors in #203 in a readable way: here are fixes to spacing only.
> formatting: Fix whitespace style

- apps/l3dtool/l3dtool.cpp
- apps/lndtool/lndtool.cpp
- components/l3d/src/l3d_file.cpp
- components/lnd/include/lnd_file.h
- components/lnd/src/lnd_file.cpp
- src/3D/L3DMesh.h
- src/3D/L3DSubMesh.h
- src/3D/LandBlock.cpp
- src/3D/LandBlock.h
- src/3D/LandIsland.cpp
- src/Gui.cpp
In order to keep the test of #203 passing and the diff minimal, I ran git format on the repo.
There was no manual intervention here. Just clang-format diff from a test in #203 and the command `git apply format.patch`
> Run git format

- src/Entities/Components/Villager.cpp
- src/Game.cpp
- src/Graphics/RenderPass.h
- src/LHScriptX/CommandSignature.h
Fixes compilation on my machine
> Add missing header includes

- src/Console.cpp
- src/Console.h
- src/Entities/Components/Transform.h
- src/Entities/Registry.cpp
- src/Entities/Registry.h
- src/Game.cpp
- src/Game.h
- src/Gui.cpp
- src/Gui.h
Add an interactive console which can run lines of script file syntax.
This allows easy testing without restarting the application.
Features copy pase, script error log, tab completion, command listing, history with arrow keys and pasting the mouse position when double clicking in the scene.
Can be expanded to save console as a script file, selecting ids from objects, parameter names and logging spdlog.
Keyboard shortcut to open is the back quote ` `` `
> Interactive Console

- src/3D/Camera.cpp
- src/Game.cpp
- src/Game.h
Follow-up to #236 with fixes to camera and hand.
> More matrix fixes

- src/GameWindow.cpp
- src/GameWindow.h
Move SDL smart pointer wrapper definition to cpp file
> window: Remove header include of SDL

- src/3D/LandIsland.cpp
- src/3D/LandIsland.h
- src/3D/Water.cpp
- src/3D/Water.h
- src/Graphics/Texture2D.cpp
- src/Graphics/Texture2D.h
- src/Gui.cpp
- src/Gui.h
- src/LHVMViewer.cpp
Clean-up code in Gui.
Move large blocks of code into logical functions.
Clean-up function structure by exiting from inside them, making code easier to read.
This is a required patch for other PRs adding to UI
> Refactor GUI code

- src/Game.cpp
- src/Game.h
- src/Gui.cpp
- src/Profiler.h
PR depends on other PRs before being merged:
Game normally updates entities at 10Hz.
Fast forward doubles the rate and slow mo halves it.
Add option in menu to set duration multiplier.
> Game: Add game logic loop

- ci/mock/CMakeLists.txt
- ci/mock/Data/WeatherSystem/gen_sky.py
- ci/mock/gen_meshes.py
- src/3D/AnimationPack.cpp
- src/3D/AnimationPack.h
- src/3D/L3DAnim.cpp
- src/3D/L3DAnim.h
- src/3D/L3DMesh.cpp
- src/3D/L3DMesh.h
- src/3D/MeshPack.cpp
- src/3D/MeshPack.h
- src/Game.cpp
- src/Game.h
- src/main.cpp
Add Mock Hand Mesh data
Factor out code for generating sky
> Fail loading on missing resources

- src/Entities/Registry.h
* Add missing header include guard.
* Add `Has` operation to check if entity has a component before casting
* Add `ToEntity` to go from component to entity
* Add `As` to go from component to another
* Add const variants and multiple template support
> Add registry functions

- src/Parsers/InfoFile.cpp
> info.dat: Add hint of wrong version parsed

- src/Game.cpp
- src/Graphics/RenderPass.h
- src/Gui.cpp
- src/Renderer.cpp
@bwrsandman Thanks for the fix
> reflection-latency - Fix latency in reflection pass

- .github/workflows/ci-system-deps.yml
This fixes issues testing PRs which don't fast-forward
> CI System Deps: Test building with action/checkout merge

- src/Gui/Console.cpp
- src/Gui/LHVMViewer.cpp
- src/Gui/LandIsland.cpp
> Gui: Fix unreferenced formal parameter warnings

- .github/workflows/ci-vcpkg.yml
- CMakePresets.json
- readme.md
> Build: Add Visual Studio 2022 preset

- src/3D/Camera.cpp
- src/3D/Camera.h
Vanilla:
Us:
@bwrsandman thanks for this
> Emulate vanilla FOV

- apps/l3dtool/l3dtool.cpp
- assets/shaders/fs_object.sc
- components/l3d/include/L3DFile.h
- components/l3d/src/L3DFile.cpp
- src/3D/L3DSubMesh.cpp
- src/3D/L3DSubMesh.h
- src/Graphics/ShaderProgram.cpp
- src/Graphics/ShaderProgram.h
- src/Renderer.cpp
- src/Renderer.h
> Add Material to Primitive

- src/3D/Camera.cpp
- src/3D/Camera.h
- src/Game.cpp
- src/Game.h
- src/Gui/Console.cpp
- src/Gui/Gui.cpp
- src/LHScriptX/Script.h
- src/main.cpp
Cleanup and making use of forward declaration to lower memory usage and speed-up compilation.
> Forward declare optimizations

- .github/workflows/ci-vcpkg.yml
Many runs are failing with
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_21.2.6-0ubuntu0.1~20.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libegl1_1.3.2-1~ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libglx-dev_1.3.2-1~ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libgl-dev_1.3.2-1~ubuntu0.20.04.1_amd64.deb  404  Not Found [IP: 52.147.219.192 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libg/libglvnd/libegl-dev_1.3.2-1~ubuntu0 …
```
> ci: Run apt update in ubuntu before installing anything

- assets/shaders/vs_terrain.sc
> shaders: Fix terrain layer indexing on SPIRV

- readme.md
Fixes #353
Note:
- not sure if we should mention the fan site
- I think it's nice to mention that the unofficial patch won't break things (at least for people who already have it installed)
> Doc: instructions to extract files

- src/Gui/Gui.h
- src/Gui/MeshViewer.cpp
> MeshViewer: Fix y-flip for non opengl

- apps/packtool/packtool.cpp
- components/pack/include/PackFile.h
- components/pack/src/PackFile.cpp
- src/Game.cpp
Small clean up to improve consistency
> Clean up asset paths

- assets/shaders/fs_water.sc
- src/3D/LandIsland.cpp
- src/3D/LandIsland.h
- src/3D/Water.cpp
- src/3D/Water.h
- src/Game.cpp
- src/Renderer.cpp
- src/Resources/Loaders.cpp
Also added Skya to the water shader (diffuse is confusingly called Sky for water) for alpha but with alpha blending off, it has no effect 
Resolves #388
> Use locator for exisiting raw files

- src/Common/Zip.cpp
- src/Common/Zip.h
Fixes build errors on master
https://github.com/openblack/openblack/runs/6405482075?check_suite_focus=true
> system deps: Fix not size_t defined error

- .github/workflows/ci-cross-compile.yml
- .github/workflows/ci-vcpkg.yml
We aren't using nasm and we aren't yet using ffmpeg
> ci: remove nasm

- .github/workflows/ci-cross-compile.yml
- .github/workflows/ci-vcpkg.yml
- CMakeLists.txt
- apps/anmtool/CMakeLists.txt
- apps/l3dtool/CMakeLists.txt
- apps/lndtool/CMakeLists.txt
- apps/morphtool/CMakeLists.txt
- apps/packtool/CMakeLists.txt
- components/anm/CMakeLists.txt
- components/l3d/CMakeLists.txt
- components/lnd/CMakeLists.txt
- components/morph/CMakeLists.txt
- components/pack/CMakeLists.txt
- src/CMakeLists.txt
- src/Game.cpp
- src/Gui/PathFinding.cpp
- src/LHScriptX/Script.cpp
Reminder: Changes to actions now only take effect when merged
> Fix last warnings and start treating them as errors

- .github/workflows/ci-cross-compile.yml
- .github/workflows/ci-vcpkg.yml
- src/Common/FileStream.cpp
- src/Common/FileStream.h
- src/Game.cpp
- src/Game.h
- src/Gui/DebugWindow.cpp
- src/Gui/DebugWindow.h
- src/Gui/Gui.cpp
- src/Gui/Gui.h
- src/LHScriptX/Lexer.cpp
- src/LHScriptX/Lexer.h
- src/Serializer/GameThingSerializer.cpp
- src/Serializer/GameThingSerializer.h
[Ubuntu 22.04 is now in public beta](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md) and will some day be the ubuntu-latest.
It comes with a GCC that is compatible with C++20 by default.
> workflows: add ubuntu-22.04

- .clang-tidy
- components/ScriptLibrary/include/LHVM/LHVM.h
- components/anm/src/ANMFile.cpp
- components/l3d/src/L3DFile.cpp
- components/morph/src/MorphFile.cpp
- components/pack/src/PackFile.cpp
- src/3D/Camera.cpp
- src/3D/L3DMesh.h
- src/Common/Bitmap16B.cpp
- src/Common/Bitmap16B.h
- src/Common/EventManager.h
- src/Common/FileStream.cpp
- src/Dynamics/LandBlockBulletMeshInterface.h
- src/ECS/Systems/DynamicsSystem.cpp
- src/Game.cpp
- src/Game.h
- src/GameWindow.cpp
- src/Graphics/IndexBuffer.cpp
- src/Graphics/ShaderManager.cpp
- src/Gui/Console.cpp
- src/Gui/Gui.cpp
- src/Gui/LHVMViewer.cpp
- src/Gui/Profiler.cpp
- src/LHScriptX/CommandSignature.h
- src/LHScriptX/Lexer.h
- src/LHScriptX/Script.cpp
- src/LHScriptX/Script.h
- src/Renderer.cpp
To enforce named casting, prevent default args in overrides, etc
> clang-tidy: google-*

- .cmake-format.py
- .github/workflows/format-check.yml
- .vcpkg/ports/bgfx/portfile.cmake
- CMakeLists.txt
- CMakeModules/ClangFormat.cmake
- CMakeModules/FindSDL2.cmake
- CMakeModules/Findspdlog.cmake
- CMakeModules/Shaders.cmake
- CMakeModules/vcpkg_android.cmake
- apps/anmtool/CMakeLists.txt
- apps/l3dtool/CMakeLists.txt
- apps/lndtool/CMakeLists.txt
- apps/morphtool/CMakeLists.txt
- apps/packtool/CMakeLists.txt
- components/ScriptLibrary/CMakeLists.txt
- components/anm/CMakeLists.txt
- components/l3d/CMakeLists.txt
- components/lnd/CMakeLists.txt
- components/morph/CMakeLists.txt
- components/pack/CMakeLists.txt
- externals/CMakeLists.txt
- src/CMakeLists.txt
- test/CMakeLists.txt
- test/mock/CMakeLists.txt
> Lint CMake Files

- src/LHScriptX/FeatureScriptCommands.cpp
- src/LHScriptX/FeatureScriptCommands.h
> Scripting: Fix const args, they're actually a list of floats

- apps/l3dtool/l3dtool.cpp
- components/l3d/include/L3DFile.h
- components/l3d/src/L3DFile.cpp
- src/3D/L3DMesh.cpp
- src/3D/L3DMesh.h
- src/Debug/MeshViewer.cpp
- src/ECS/Archetypes/AbodeArchetype.cpp
- src/ECS/Archetypes/PotArchetype.cpp
- src/ECS/Archetypes/PotArchetype.h
- src/ECS/Components/Pot.h
- src/ECS/Components/StoragePit.h
- src/Enums.h
- src/LHScriptX/FeatureScriptCommands.cpp
- src/LHScriptX/FeatureScriptCommands.h
This PR does three things:
* Decodes the Extra Metrics L3D block.
* Implements the `CREATE_POT` script command
* Adds the Wood and Food piles to storage pits
> Piles and storage pit

- src/LHScriptX/FeatureScriptCommands.cpp
- src/LHScriptX/FeatureScriptCommands.h
extracting unrelated commit out of #489
> Spawn dead trees

- src/3D/LandIsland.cpp
- src/Graphics/FrameBuffer.cpp
This reverts commit d0c37ca7244699721cfbd84de30b9e096c8c7372.
> metal: Cannot use swizzled texture as framebuffer

- .clang-format-ignore
- .github/workflows/ci-vcpkg.yml
- externals/CMakeLists.txt
- externals/imgui_user/imgui_impl_sdl.cpp
- externals/imgui_user/imgui_impl_sdl.h
- src/Debug/Gui.cpp
- src/Debug/Gui.h
- src/Game.cpp
> Gui: Use imgui's official SDL2 interface

- apps/lndtool/lndtool.cpp
- components/anm/src/ANMFile.cpp
- src/3D/Camera.cpp
- src/3D/Camera.h
- src/Common/FileSystem.h
- src/Common/StringUtils.cpp
- src/Common/StringUtils.h
- src/Debug/Gui.cpp
- src/ECS/Registry.h
- src/Game.cpp
- src/Game.h
- src/Renderer.cpp
- test/mock/CMakeLists.txt
extracting misc and prep commits from https://github.com/openblack/openblack/pull/489
> Temple creature camera base

- .github/workflows/ci-vcpkg.yml
Tweak offsets now that position and angle is different.
Set backbuffer capture to the right resolution.
Proof of concept #561
> screenshots: Get new reference images

- src/3D/CreatureBody.cpp
- src/3D/CreatureBody.h
- src/Common/StringUtils.cpp
- src/Creature/CreatureMind.h
- src/ECS/Archetypes/CreatureArchetype.cpp
- src/ECS/Archetypes/CreatureArchetype.h
- src/ECS/Components/Creature.h
- src/Enums.h
- src/Game.cpp
- src/LHScriptX/FeatureScriptCommands.cpp
- src/LHScriptX/FeatureScriptCommands.h
- src/Resources/Loaders.cpp
- src/Resources/Loaders.h
- src/Resources/Resources.h
extracting creature content out of https://github.com/openblack/openblack/pull/489
> Spawn creature

- .github/workflows/format-check.yml
- CMakeModules/ClangFormat.cmake
Cherry-picked #595 from @FalseIlyu
> Update to use clang format 15

- src/Debug/Gui.cpp
- src/Level.cpp
- src/Level.h
Should fix the bug found by @bwrsandman in #593 .
> Fix landscape path before use.

- .github/workflows/ci-cross-compile.yml
- CMakeLists.txt
- apps/anmtool/tiny_gltf.h
- apps/l3dtool/tiny_gltf.h
- vcpkg.json
This reverts commit 4b0df2ba8831bc1b27dad9096ea74e06a81f792a.
Closes #519, #174 and #533
> Enable x86, arm64 and webasm cross compile tests

- src/3D/L3DSubMesh.cpp
The matrix used to compute the bounding box of a vertex group span in a subMesh is only depedent on the span and not the individual vertex.
Currently we compute the transformation matrix of the vertex span for each vertex in the span, i moved it so we only do it once per span.
> Generate vertexGroupSpan matrix only once

- .github/workflows/ci-cross-compile.yml
- .github/workflows/format-check.yml
- android/app/build.gradle
- android/app/src/main/java/org/openblack/app/FileSystemInterop.java
The workflows were checking out the pull request base and not the changes so errors slipped through and fixes don't show up as fixed.
> Fix android tests

- src/ECS/Archetypes/PlayerArchetype.cpp
- src/ECS/Archetypes/PlayerArchetype.h
- src/ECS/Components/Player.h
- src/ECS/Components/WallHug.h
- src/ECS/Systems/Implementations/PlayerSystem.cpp
- src/ECS/Systems/Implementations/PlayerSystem.h
- src/ECS/Systems/PlayerSystemInterface.h
- src/Game.cpp
- src/LHScriptX/FeatureScriptCommands.cpp
- src/LHScriptX/FeatureScriptCommands.h
- src/Locator.cpp
- src/Locator.h
Extracting commit from https://github.com/openblack/openblack/pull/489 and clean-up.
> ECS: Add player archtetype

- src/3D/TempleInterior.cpp
- src/3D/TempleInterior.h
- src/3D/TempleInteriorInterface.h
- src/Debug/Gui.cpp
- src/Debug/Temple.cpp
- src/Debug/Temple.h
- src/ECS/Archetypes/CitadelArchetype.cpp
- src/ECS/Archetypes/CitadelArchetype.h
- src/ECS/Archetypes/PlayerArchetype.cpp
- src/ECS/Components/Temple.h
- src/ECS/Systems/Implementations/PlayerSystem.cpp
- src/ECS/Systems/Implementations/PlayerSystem.h
- src/ECS/Systems/PlayerSystemInterface.h
- src/Game.cpp
- src/LHScriptX/FeatureScriptCommands.cpp
- src/Locator.cpp
- src/Locator.h
Extracting commits from https://github.com/openblack/openblack/pull/489 and clean-up.
Depends on:
> Temple Interior and Exterior

- .github/workflows/ci-cross-compile.yml
This is clearly a bug in bgfx.cmake
> Add OpenGL dependency for x86 bgfx

- components/l3d/src/L3DFile.cpp
- src/3D/LandIsland.cpp
- src/InfoConstants.cpp
- src/InfoConstants.h
- src/Parsers/InfoFile.cpp
> Add support for B&W files from v1.00

- src/Common/RandomNumberManager.h
The template accepts `std::array` with `size > 0`. For a vector, it will check in debug but in release calling the function on an empty vector results in undefined behaviour.
Example usage:
```c++
static constexpr auto wooshingNoiseIds = std::array<audio::SoundId, 4> {
audio::SoundId::G_Woosh_01,
audio::SoundId::G_Woosh_02,
audio::SoundId::G_Woosh_03,
audio::SoundId::G_Woosh_04,
};
const auto wooshNoiseId = static_cast<entt::id_type>(Locator::rng::value().Choose(wooshingNoiseIds));
```
```c++
std::vector<audio::SoundId> wooshingNoiseIds;
wooshingNoiseIds.push_back(audio::SoundId::G_Woosh_01);
wooshingNoiseIds.push_back(audio::SoundId::G_Woosh_02);
wooshingNoiseIds.push_back(audio::SoundId::G_Woosh_03);
wooshingNoiseIds.push_back(audio::SoundId::G_Woosh_04);
const auto wooshNoiseId = …
```
> rng: Add choose function to select item from container

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
- android/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- android/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
- android/app/src/main/java/org/libsdl/app/SDL.java
- android/app/src/main/java/org/libsdl/app/SDLActivity.java
- android/app/src/main/java/org/libsdl/app/SDLAudioManager.java
- android/app/src/main/java/org/libsdl/app/SDLControllerManager.java
- android/app/src/main/java/org/libsdl/app/SDLSurface.java
- android/app/src/main/java/org/openblack/app/FileSystemInterop.java
- src/FileSystem/AndroidFileSystem.cpp
- src/Game.cpp
Solves #687
This solves three problem i had when launching the game which are, crash with SDL (corrected by updating SDL java interface), changing the JavaFilesystem recursive directory search as it doesn't give the file path relative to the first directory meaning the path are wrong when trying to open them, finally i openned the soundfile using `soundPack.Open(fileSystem.ReadAll(f));` as the normal open use std::filesystem to open files.
There also seems to be a problem with the game path but my installation is non standard and is inside the user document folder instead of /data/local/tmp/bw.
Due to this fact and until i have test feedback on other android systems this PR shall be kept a draft.
An other prerequisite is investigating this \:
> Android filesystem fix

- apps/anmtool/tiny_gltf.h
- apps/l3dtool/tiny_gltf.h
The current version of gltf fails on gcc 14
Requires:
> apps: Update gltf to v2.8.10

- src/Audio/AudioPlayer.cpp
- src/Locator.cpp
> Version logging

- CMakeLists.txt
- components/lnd/src/LNDFile.cpp
- src/3D/L3DMesh.cpp
- src/3D/LandBlock.cpp
- src/3D/Sky.cpp
- src/Camera/Camera.cpp
- src/Camera/DefaultWorldCameraModel.cpp
- src/Common/RandomNumberManager.h
- src/Debug/MeshViewer.cpp
- src/Debug/Profiler.cpp
- src/Dynamics/LandBlockBulletMeshInterface.h
- src/ECS/Archetypes/CameraBookmarkArchetype.cpp
- src/ECS/Components/Transform.h
- src/Game.cpp
- src/InfoConstants.cpp
- src/Input/GameActionMap.cpp
- src/LHScriptX/FeatureScriptCommands.cpp
- src/LHScriptX/Script.cpp
- src/Renderer.cpp
- src/main.cpp
Changes towards the accomplishment of #656, implements #522
Depends on 
This apply only in /src
> C++23 transition

- .github/workflows/ci-cross-compile.yml
- CMakeLists.txt
- CMakeModules/ios.toolchain.cmake
- CMakePresets.json
- readme.md
- src/CMakeLists.txt
- src/Graphics/MetalViewHelper.mm
> platforms: Add configuration for ios

- .github/workflows/ci-vcpkg.yml
Update runners using Clang 17 to Clang 18 to support enumerate views.
> Update runners to Clang 18

- .github/workflows/ci-cross-compile.yml
- readme.md
> Enable linux x86 bit and arm64 cross compilation
