src/3D/LandIsland.cpp, src/3D/LandIsland.h, src/Game.cpp, src/GameWindow.h, src/Graphics/Shader.cpp, src/LHScriptX/Script.h
- MapMaterial refers both to a type (struct) and a variable (member of struct Country). I had to rename it to compile with gcc. It is probably a good practice to do so.
- Some c functions were used without proper includes
- The use of backslash in paths is only compatible with windows, so I added an `#ifdef` for Unices
=> Fixes for building with GCC and working on Linux

README.md
the more modern cmake command can also be used on Windows with MSVC
toolchain, only the generator must be specified
```
cmake -S . -B build -G "Visual Studio 16 2019" -A x64
cmake --build build
```
=> readme: use more modern cmake command for linux

src/Video/Bink/GetBitContext.cpp
register deprecated with C++17
https://en.cppreference.com/w/cpp/language/storage_duration
the register keyword broke the clang compilation
=> Bink: ISO C++17 does not allow 'register' storage class specifier

src/3D/MeshPack.cpp
got error
```
/home/nero/repos/openblack/src/3D/MeshPack.cpp: In member function ‘void OpenBlack::MeshPack::loadTextures(OpenBlack::File&)’:
/home/nero/repos/openblack/src/3D/MeshPack.cpp:162:3: error: ‘itoa’ was not declared in this scope
162 |   itoa(tex.first, sBlockID, 16);
|   ^~~~
```
```
g++ --version
gcc (GCC) 9.1.0
```
alternative (and info that iota is not ansi C from here:
https://stackoverflow.com/a/6462973
Edit: got a CI job with the error, exciting :)
https://travis-ci.org/NeroBurner/openblack/jobs/579247589
=> use snprintf because iota is not ansi C

components/ScriptLibrary/include/LHVM/LHVM.h, components/ScriptLibrary/include/LHVM/OpcodeNames.h, components/ScriptLibrary/include/LHVM/VMInstruction.h, components/ScriptLibrary/include/LHVM/VMScript.h, components/ScriptLibrary/include/LHVM/VMTask.h, src/3D/Camera.h, src/3D/Hand.h, src/3D/LandCell.h, src/3D/SkinnedModel.h, src/3D/Sky.h, src/3D/Water.h, src/AllMeshes.h, src/Common/Bitmap16B.h, src/Common/CmdLineArgs.h, src/Common/Types.h, src/Game.h, src/GameWindow.h, src/GitSHA1.h, src/Graphics/DebugDraw.h, src/Graphics/IndexBuffer.h, src/Graphics/Mesh.h, src/Graphics/OpenGL.h, src/Graphics/ShaderManager.h, src/Graphics/ShaderProgram.h, src/Graphics/Texture2D.h, src/Graphics/Texture2DArray.h, src/Graphics/VertexBuffer.h, src/LHVMViewer.h, src/Video/Bink/GetBitContext.h, src/Video/VideoPlayer.h
A large portion of the project used double include guards. There were
more `#pragma`s than the traditional ones, so I guessed that was the
original intention.
=> Fix include guards

src/Graphics/OpenGL.h
throws some errors on my mingw toolchain
=> Graphics: don't redefine GLEW_STATIC if already defined

src/GameWindow.cpp
Glew can't open glx display when it's running on wayland session and thus
returns an error. But glXGetProcAddress is fully usable on wayland, so we
can just ignore the "no glx display" error.
Note that GLEW_ERROR_NO_GLX_DISPLAY needs glew >= 2.1. Older versions assume
that glx display is always available and will just crash.
source: https://github.com/SuperTux/supertux/commit/06976f8ed70c7137807b7b312c07f5698832be9a
=> Fixed glew on wayland

CMakeLists.txt, src/CMakeLists.txt, src/Common/File.h, src/Common/FileSystem.h
test if <filesystem> header is available and use it. If not fall back to
use <experimental/filesystem>. This fixes clang builds
=> use std::filesystem if available

CMakeLists.txt
Ubuntu 18.04 has cmake 3.10, and it successfully builds on it
https://travis-ci.org/NeroBurner/openblack/jobs/579421302
=> cmake: require 3.10 as minimum version

CMakeLists.txt
Add `USE_SUBMODULE` option which is on by default to maintain current
behaviour.
Turing off `USE_SUBMODULE` will use find_package instead of using submodules and
subdirectories. This option is prefered on linux distributions which
have packages for entt and spdlog.
This option will be switched off for packaging on the Arch Linux User Repository (AUR).
The two extern dependencies are available already on Arch:
* https://www.archlinux.org/packages/community/any/spdlog/
* https://aur.archlinux.org/packages/entt/
=> cmake: optionally use externs (on by default)

src/LHVMViewer.cpp
- don't use char* directly as formatter string, feed it into a format
- use size_t for selected variable
=> LLVMViewer: fix some warnings

.travis.yml
spdlog provided by Ubuntu 18.04 is too old, we need v1.3.0 at least
=> ci: travis: use Hunter for Ubuntu 18.04 build

CMakeLists.txt
Ubuntu 18.04 (bionic) has cmake 3.10 and does not support to link
libraries to an interface target directly. The option was introduced
with cmake 3.11
=> cmake: fix interface target linking for cmake 3.10

ci/Dockerfile.ubuntu.template, src/3D/Camera.cpp, src/3D/Camera.h, src/3D/Sky.cpp, src/3D/Sky.h, src/3D/Water.cpp, src/3D/Water.h, src/CMakeLists.txt, src/Game.cpp, src/Game.h, src/GameWindow.cpp, src/GameWindow.h, src/Graphics/OpenGL.h, src/Renderer.cpp, src/Renderer.h
This change decouples some of the rendering logic from the Game and Window Class and puts them in a Rendering Class on its own.
This class will grow into a proper renderer, adding abstractions to the engine, maintaining a rendering thread, its own settings and acceleration structures.
This change was also done in a future-proofing way to allow changes of rendering api and different windowing apis.
* Moved context from game window to Renderer.
* Moved the message callback to the renderer with itself as the user param.
* Moved most of the rendering logic from Game into Renderer.
Bonus: Moved the `GLEW_STATIC` define to CMake so it is now a project-wide define and doesn't need define guards.
=> Add Renderer Class

src/Game.cpp, src/GameWindow.cpp, src/Renderer.cpp
- disable SDL_GL_MULTISAMPLEBUFFERS
- disable SDL_GL_MULTISAMPLESAMPLES
seems the previous PR fell out with the rebase
https://github.com/openblack/openblack/pull/70/commits/6195fd7bee34fba52aa896b1bf708eeda618634f
=> Renderer: disable MULTISAMPLE to fix OpenGL on wayland

src/3D/L3DSubMesh.cpp, src/3D/L3DSubMesh.h, src/3D/LandBlock.cpp, src/3D/LandBlock.h, src/3D/Water.cpp, src/Graphics/DebugLines.cpp, src/Graphics/IndexBuffer.cpp, src/Graphics/IndexBuffer.h, src/Graphics/Mesh.cpp, src/Graphics/Mesh.h, src/Graphics/VertexBuffer.cpp, src/Graphics/VertexBuffer.h
Refactoring VertexDecl mainly.
The constructor has been greatly simplified to an api that looks a lot like bgfx.
Remove a lot of explicit `sizeofs` that are mostly opengl specific.
Moved the `VertexDecl` to vertex buffer.
Converted all usages of vertex attributes to this api.
Force alignment on 4 bytes in terrain.
Fix a few issues.
This includes #94
=> Vertex attribs refact

src/3D/L3DMesh.cpp, src/3D/L3DSubMesh.cpp, src/3D/LandBlock.cpp, src/3D/LandBlock.h, src/3D/LandIsland.cpp, src/3D/MeshPack.cpp, src/3D/Sky.cpp, src/3D/Water.cpp, src/Graphics/DebugLines.cpp, src/Graphics/IndexBuffer.cpp, src/Graphics/IndexBuffer.h, src/Graphics/Mesh.cpp, src/Graphics/Mesh.h, src/Graphics/ShaderProgram.cpp, src/Graphics/ShaderProgram.h, src/Graphics/Texture2D.cpp, src/Graphics/Texture2D.h
Add enums for opengl types.
Remove include of opengl from headers and move them to impl files.
=> OpenGL clean-up in headers

src/Graphics/IndexBuffer.cpp, src/Graphics/IndexBuffer.h, src/Graphics/Mesh.cpp
Move index binding (`glBindBuffer(GL_ELEMENT_ARRAY_BUFFER...)` to the index
class.
Remove `GetIBO` to discourage external use of `_ibo`.
=> index buffer: Add function to bind itself

src/3D/Water.cpp, src/Game.cpp, src/Graphics/FrameBuffer.cpp, src/Graphics/FrameBuffer.h, src/MeshViewer.cpp, src/Renderer.cpp, src/Renderer.h
Store Texture in unique_ptr.
Use uint32_t as width and height.
Pass format to texture. Use Format enum.
Texture2D get returns a reference.
Add optional depth stencil to framebuffer
=> Framebuffer: Remove OpenGL from header

src/Graphics/FrameBuffer.cpp, src/Graphics/FrameBuffer.h, src/Graphics/Texture2D.cpp, src/Graphics/Texture2D.h
One can reasonably assume that the textures will not have dimensions of
more than 65536.
=> Texture: Store dimensions in 16 bits

src/Game.cpp, src/Renderer.cpp, src/Renderer.h
`-v`: enable vsync (defaulted to false)
`-b`, `-f`: windowing borderless or fullscreen respecively. If both are supplied, borderless takes precedence. If none are supplied, windowed is used.
=> Add convenience commandline parameters

CMakeLists.txt
The option is off by default but if enabled, it will find and create the spirv-tools target from the system installed library (if it doesn't exist, it will error here).
Thanks to this bit of code in bgfx.cmake and the alias library, bgfx.cmake will use the system instead of building it itself.
https://github.com/JoshuaBrookover/bgfx.cmake/blob/master/cmake/3rdparty/spirv-tools.cmake#L11-L13
=> cmake: add option to use system spirv-tools in bgfx

src/Gui.cpp, src/Gui.h
Transient buffers are destroyed and recreated at every frame.
The default size of a transient buffer (`init.limits.transientVbSize`) is
rather large and this causes the destruction, recreation and upload of
large GPU buffers.
A dynamic buffer is used instead which is recreated only when the ui needs
more space for vertices and indices. This prevents the recreation of the
buffers and leaves the uploads to only the size of buffers needed to be
done every frame.
On my machine this means a difference of 10ms:
Current Master:
This PR:
Related issue https://github.com/bkaradzic/bgfx/issues/1023
Note that the profiler as it is does not record the Update Vertex time, this is because I made local changes to the bgfx internal stats but did not push them since they were pretty hacky.
=> ui: remove use of transient buffers

src/3D/AxisAlignedBoundingBox.h, src/3D/L3DMesh.h, src/3D/L3DSubMesh.cpp, src/3D/L3DSubMesh.h, src/Entities/Registry.cpp, src/Entities/Registry.h, src/Game.cpp, src/Game.h, src/Graphics/DebugLines.cpp, src/Graphics/DebugLines.h, src/Gui.cpp, src/MeshViewer.cpp, src/Renderer.cpp, src/Renderer.h
Add bounding boxes to `L3DSubMesh` which can be useful for future culling, picking and physics.
Note that these are axis-aligned and even in the debug view, I don't bother rotating them yet.
They aren't added to the Island blocks either but this can be done at a later time. This would be useful for physics and accelerating ray intersection.
=> L3DSubMesh Bounding Boxes

assets/shaders/varying.def.sc, assets/shaders/vs_line_instanced.sc, assets/shaders/vs_object_instanced.sc, src/3D/L3DMesh.cpp, src/3D/L3DMesh.h, src/3D/L3DSubMesh.cpp, src/3D/L3DSubMesh.h, src/Entities/Components/Transform.h, src/Entities/Registry.cpp, src/Entities/Registry.h, src/Game.cpp, src/Graphics/DebugLines.cpp, src/Graphics/DebugLines.h, src/Graphics/Mesh.cpp, src/Graphics/Mesh.h, src/Graphics/ShaderManager.cpp, src/Graphics/Shaders/vs_line_instanced.bin.h, src/Graphics/Shaders/vs_object_instanced.bin.h, src/Profiler.h, src/Renderer.h
Major re-write and optimization of registry draw models code.
An option to draw instanced was added to Debug Lines and `L3DMesh`/`L3DSubMesh`.
The traversal of entities is now done in `PrepareDraw` and it does this to count the number of different meshes ids.
Once that's done, a single buffer in allocated (and reallocated only if more meshes need to be drawn that the buffer has room for).
A second traversal populates this buffer with uniforms for all the entities grouped by mesh ids. This means that this buffer will have all the transforms of one type of tree mesh followed by all the transforms of another mesh etc.
The call to `PrepareDraw` is only done when necessary. This means if nothing changes in the scene (for the entities), then no update is done. This is implemented with a `dirty` …
=> Entities Instance Draw

src/3D/Sky.cpp, src/3D/Sky.h, src/Renderer.cpp
The sky was not rendered in the water reflection because due to the inverted camera, the winding order is reversed.
This fixes it by letting sky know which winding order to use.
=> sky: inverse culling on reflection

src/Entities/Registry.cpp, src/Entities/Registry.h, src/Game.cpp, src/Game.h, src/Graphics/DebugLines.cpp, src/Graphics/DebugLines.h, src/Gui.cpp, src/Renderer.cpp, src/Renderer.h
Re-enable drawing streams with a imgui option.
Move construction of streams to `PrepareDrawUploadUniforms`.
Store mesh of bounding box and stream in Registry.
=> streams: Build Streams as a single mesh

src/3D/L3DMesh.cpp, src/3D/LandBlock.cpp, src/3D/LandBlock.h, src/3D/LandIsland.cpp, src/Graphics/DebugLines.cpp, src/Graphics/IndexBuffer.cpp, src/Graphics/RenderPass.h, src/Graphics/Texture2D.cpp, src/Graphics/VertexBuffer.cpp, src/Renderer.cpp
Enable bgfx multi-threaded mode.
Make uploads of texture and mesh data more bgfx friendly with `bgfx::Memory` and sparsely placed `bgfx::frame` calls during loading.
=> Move bgfx dispatch to its own thread

CMakeModules/Shaders.cmake, assets/shaders/fs_object.sc, assets/shaders/fs_terrain.sc, assets/shaders/varying.def.sc, assets/shaders/vs_terrain.sc, src/3D/LandBlock.cpp, src/3D/LandIsland.cpp, src/3D/LandIsland.h, src/3D/Sky.cpp, src/Game.cpp, src/GameWindow.cpp, src/GameWindow.h, src/Graphics/FrameBuffer.cpp, src/Graphics/Mesh.cpp, src/Renderer.cpp, src/Renderer.h
These changes add DirectX support. I was adding D3D11 only but it seems to fix D3D12 too.
You can now start openblack with `-r` to select the backend api.
This does break the sky on OpenGL since it seems bgfx has a bug for the RGB5A1 textures by having the colors in the wrong order (https://github.com/bkaradzic/bgfx/pull/1932).
Other than that, it seems to be feature parity.
D3D9 still has bugs but is not a priority
=> DirectX support

CMakeLists.txt, CMakeModules/Shaders.cmake, README.md, apps/g3dtool/CMakeLists.txt, apps/l3dtool/CMakeLists.txt, apps/lndtool/CMakeLists.txt, azure-pipelines-ci.yml, azure-pipelines/templates/linux-build.yml, azure-pipelines/templates/windows-build.yml, azure-pipelines/templates/windows-dependencies.yml, components/ScriptLibrary/CMakeLists.txt, components/g3d/CMakeLists.txt, components/l3d/CMakeLists.txt, components/lnd/CMakeLists.txt, external/imgui/CMakeLists.txt, src/Gui.cpp
depend on bgfx's install target from: https://github.com/openblack/bgfx.cmake
this is now baked into the compile farm docker image for Linux builds, and for Windows builds precompiled binaries are pulled from here: https://github.com/openblack/bgfx.cmake/releases/tag/latest
our current version of bgfx is forked here: https://github.com/openblack/bgfx and includes some changes by @bwrsandman  https://github.com/bkaradzic/bgfx/compare/master...openblack:master
with no longer needing to build bgfx alongside openblack we have cut CI times down to 2 minutes:
couple of things before merging this:
* ~~need to add option `OPENBLACK_BUILD_BGFX` to build bgfx if people don't want to make bgfx for whatever reason~~ 
001d3a1
* ~~weird graphical bugs with latest bgfx~~ (specifically …
=> Use find_package(bgfx CONFIG) and make Azure Pipelines faster

CMakeLists.txt, CMakeModules/Shaders.cmake
Fix OPENBLACK_BUILD_BGFX build option path for bgfx_shaders.sh
Fix-up -fPIC declarations from bgfx and bgfx::shaderc alias
=> shaderc: Fix multiple include locations

README.md
By default on windows the vcpkg triplet is 32-bit and this can confuse new devs.
On Linux it is 64 bit so the flag is not needed.
=> Specify 64 bit triplet for vcpkg on windows

azure-pipelines-ci.yml
Build platform is not available in Linux test and unused in test null renderer
=> Fixup parameters

.clang-format, apps/lndtool/lndtool.cpp
There is an inconsistency between the clang-format on my machine and the ci.
My clang format will try to fix the braces as such:
```diff
// clang-format version 9.0.1
-       union
-       {
+       union {
```
=> Fix union braces

apps/l3dtool/l3dtool.cpp, assets/shaders/varying.def.sc, assets/shaders/vs_object.sc, assets/shaders/vs_object_instanced.sc, components/l3d/include/l3d_file.h, components/l3d/src/l3d_file.cpp, src/3D/L3DMesh.cpp, src/3D/L3DMesh.h, src/3D/L3DSubMesh.cpp, src/3D/L3DSubMesh.h, src/3D/Sky.cpp, src/Entities/Registry.cpp, src/Game.cpp, src/Game.h, src/Gui.cpp, src/MeshViewer.cpp, src/Renderer.cpp, src/Renderer.h
Improved the representation of boned meshes by using the vertex groups in L3D file.
Updated the object shader (not the instanced one) to use default pose as model matrices.
The vertex blending is still not implemented.
~~The instanced drawing does not use the bones matrices yet.~~
The concept of states of animation is not yet done. I would like to avoid putting that in the mesh as
as mesh is not a game object. There should only be one instance of a type of mesh regardless of the number of instances drawn. The same mesh should be drawn several times with different matrix values.
Updates to root position is not implemented in single mesh drawin. This means no animation and the test creature will be centered at 0 coordinate. This can be fixed by offsetting all bone indices by one.
I added …
=> Render boned meshes

azure-pipelines/templates/test-null-renderer.yml, src/CMakeLists.txt, src/Game.cpp, src/Game.h, src/main.cpp
By default openblack will log to a file.
Specifying `--logfile stdout` will log to terminal.
Default level is now debug and any number higher than 0 will be a higher
level such as info, warning and error.
=> logging: Add log to file and level options

src/Entities/Components/Transform.h, src/Game.cpp, src/LHScriptX/FeatureScriptCommands.cpp
This is a pre-requisite for physics / ray casting and likely useful for path planning.
Clean-up creation of transforms with use of euler angle functions from
glm.
Replace uses of `glm::pi / 2` with glm::half_pi.
Replace uses of PI for 180 degree rotation with explicit use of
`glm::radians(180.0f)`.
=> transform: use a matrix instead of euler angles

components/ScriptLibrary/src/LHVM.cpp
Null terminated strings weren't being read properly in LHVM loader. Making the whole file unreadable and crashing.
=> Fix variable name loading in LHVM chl loader.

src/3D/AnimationPack.cpp, src/3D/AnimationPack.h, src/3D/L3DAnim.cpp, src/3D/L3DAnim.h, src/3D/L3DMesh.cpp, src/3D/L3DMesh.h, src/3D/LandIsland.cpp, src/3D/MeshPack.cpp, src/3D/MeshPack.h, src/3D/Sky.cpp, src/3D/Water.cpp, src/Common/Bitmap16B.cpp, src/Common/Bitmap16B.h, src/Common/FileSystem.cpp, src/Common/FileSystem.h, src/Console.cpp, src/Entities/Components/Abode.h, src/Entities/Components/Tree.h, src/Entities/Components/Velocity.h, src/Game.cpp, src/Game.h, src/Gui.cpp
Cleaning up the file system interface a little by using `fs::path` instead of string where it is logical.
Moving free uses of hard coded file paths to centralized place.
=> Filesystem and cleanup

src/3D/Camera.cpp, src/3D/Camera.h
This has two things:
* If you tried to move and rotate the camera at the same time you won't be able to stop moving as the view matrix will have changed since the `_velocity` was last set.
* Unintentionally, my changes made it possible to recalculate velocity on camera rotation (view matrix change).
=> camera-fix - This fixes velocity issues when rotating and moving at the same time

apps/l3dtool/l3dtool.cpp, components/l3d/include/L3DFile.h, components/l3d/src/L3DFile.cpp, src/3D/L3DMesh.cpp, src/3D/L3DMesh.h
This allows fetching building door positions.
The flag 0x800 is correctly labeled.
There was an error with the placement of extra data which has been corrected.
Docs are updated as well.
=> L3DFile: Fix extra data interpretation

src/Common/FileSystem.h, src/Game.cpp, src/LHScriptX/FeatureScriptCommands.cpp, src/LHScriptX/ScriptingBindingUtils.h, src/Serializer/Common.h, src/Serializer/FotFile.cpp, src/Serializer/FotFile.h, src/Serializer/GameThingSerializer.cpp, src/Serializer/GameThingSerializer.h
Each released Scene is accompanied by a `Landscape/*.fot` file which contains footpath information and is of the same type as saved game file format. 
This also means that this parser is the beginning of a save file parser.
=> fot: Add footpath file parsing

src/LHScriptX/FeatureScriptCommands.cpp
Fix bad rotation of abodes.
When assigning homes to villagers based on door positions, there are a lot less town-less villagers with this fix.
=> Scripts: Make size and rotation in uniform manner

src/3D/Camera.cpp, src/3D/Camera.h, src/Entities/Registry.cpp, src/Entities/Registry.h, src/Game.h, src/Gui.cpp, src/Gui.h
PR depends on other PRs before being merged:
Add view of villager names as is in Vanilla when pressing the "S" key
The option is enabled in the menu under Debug/Villager Names/Show
The villager names are rendered with the default font (TODO: use font from assets. They need to be loaded as ImGui font) in ImGui. The tint of the window might be different from vanilla as well as the default height and shape of the arrows.
Vanilla also used arrows for every window even if they were stacked. This was not done in this PR.
I replicated the way that vanilla prevents overlapping boxes: by testing for intersection at insert time and moving up if there is.
There is some depth-based culling and possible line of sight culling in vanilla which was not done in this PR.
The color of the text is based on …
=> Add Villager Names

src/Serializer/GameThingSerializer.cpp
In GameThingSerializer `fmt/fmt.h` can't be found as it is not a direct
dependency provided by CMake. Use the bundled `fmt.h` from spdlog
instead.
=> Use bundled fmt/fmt.h from spdlog

apps/packtool/packtool.cpp, ci/mock/CMakeLists.txt, ci/mock/Data/Textures/gen_textures.py, ci/mock/gen_zeroed_file.py, components/pack/include/PackFile.h, components/pack/src/PackFile.cpp, src/Game.cpp, src/Game.h, src/InfoConstants.h, src/Parsers/InfoFile.cpp, src/Parsers/InfoFile.h
Add all Infos structures
Move job of reading Infos to own class.
Fix MagicInfo size by adding 4 bytes.
Re-enable magic type debugging.
This is needed for work being done on villager states in which assigning villagers to abodes needs values from `GAbodeInfo::maxCapacity`.
Relates to #171
=> info.dat: Fully read file

CMakeLists.txt, azure-pipelines/templates/linux-build.yml, azure-pipelines/templates/windows-build.yml, src/3D/Camera.h, src/CMakeLists.txt, src/Common/FileStream.cpp, src/Entities/Registry.cpp, src/GameWindow.cpp, src/Gui.cpp, src/LHScriptX/Script.cpp, src/LHVMViewer.cpp, src/Serializer/GameThingSerializer.h
I took a minute and went through all the warnings I get on Linux.
Found a few soft bugs and potential undefined behaviour.
I set an option to treat warnings as errors and enabled them on azure for Linux only.
I haven't gone through the warnings on MSVC, they seem too numerous and I don't want to deal with `fopen_s`.
=> Fix Warnings on Builds

src/Common/MeshLookup.h, src/Entities/Components/Mesh.h, src/Entities/Registry.cpp, src/Game.cpp, src/LHScriptX/FeatureScriptCommands.cpp
By adding a mesh component, access to mesh id and sub mesh id are much quicker (struct is aligned on 8 bytes) and easier to do with EnTT.
Getting mesh Ids is now done at entity creation time.
Rendering is done with one `Each` call. No more need to use look-up tables. This greatly simplifies the amount of code needed.
Changing villager roles will have to be accompanied by changes to the mesh component.
The debug bounding boxes are now properly oriented after a fix.
Open question: for some reason some of the bounding boxes use different submesh ids. Why is this?
Depends on:
=> components: Add Mesh Component and use for drawing

src/Entities/Components/Footpath.h, src/Entities/Registry.h, src/Serializer/Common.h, src/Serializer/FotFile.cpp, src/Serializer/GameThingSerializer.cpp, src/Serializer/GameThingSerializer.h
This is part of the villager state machine work that I am doing.
The footpath link is a look-up entry for associating buildings (`MultiMapFixed` and `PlannedMuliMapFixed`) to one or more footpaths.
This is used when a living wants to navigate to a building using a footpath.
The `FotFile` stores `FootpathLinkSave` which has a list of footpaths and position.
The footpaths in the list are duplicates of those found in the footpath list.
Eventually, the footpath links are traversed to associate themselves with loaded buildings (this is not done yet as MultiMapFixed is not yet added).
The solution here was to add equality operators to the `GameThingSerializer` structs and use `std::find` to get the references to the original footpaths.
=> Footpath link

external/imgui/CMakeLists.txt, external/imgui/imgui_user.cpp, external/imgui/imgui_user.h, src/Gui.cpp
Enums for villager debug attributes were all displayed as 32 bit ints when
most of them were fitting in a 8 bit enum.
Add imgui_user to compilation.
Add Combo and ListBox template to take any size index and arrays of string
views for string representation.
Use this template on life stage, sex, tribe, role and task
=> Gui: Member size bug in villager debug

src/3D/AnimationPack.cpp, src/3D/L3DAnim.cpp, src/3D/L3DMesh.cpp, src/3D/L3DSubMesh.cpp, src/3D/LandIsland.cpp, src/3D/MeshPack.cpp, src/3D/Sky.cpp, src/CMakeLists.txt, src/Common/MeshLookup.h, src/Game.cpp, src/Game.h, src/GameWindow.cpp, src/Graphics/ShaderProgram.cpp, src/Graphics/Texture2D.cpp, src/LHScriptX/FeatureScriptCommands.cpp, src/Parsers/InfoFile.cpp, src/Renderer.cpp, src/Serializer/GameThingSerializer.cpp, src/main.cpp
This PR adds granularity to logs. This frees us up to the possibility of adding more log messages without worrying about spamming everyone's logs.
We make use of different loggers which can be set to each have different levels in the command line.
We also use the `SPDLOG_LOGGER` macro which lets the log show the line and file name associated with a log message.
Additionally, this allows us to compile away log messages of low severity by setting the `SPDLOG_ACTIVE_LEVEL` define.
Adding a category (audio for example) is as simple as adding it to `LoggingSubsystem` and `LoggingSubsystemStrs` in `Game.h`. The loggers will be created automatically and the commandline arguments and help text will be added also. Simply use `spdlog::get("new logger's name")`
The purpose of this PR is to allow …
=> Add categories to logs

.clang-format-ignore, .github/workflows/clang-format-check.yml, src/Gui.cpp
https://github.com/marketplace/actions/clang-format-lint
This doesn't use the cmake clang-format, so it requires slightly different formatting (especially in the ignore file).
It is possible to have it automatically commit formatting fixes with https://github.com/marketplace/actions/add-commit
It does run much faster (~15s) than using the cmake clang-format because it doesn't need to install or configure anything .
=> Add clang-format action

readme.md
Since VSCode works the same on Windows and Linux, I split the OS-specific section into vcpkg/system and IDE categories.
=> Update the readme for cmake presets building

CMakePresets.json
These were leftover from a previous iteration. Since I didn't supply a 32-bit preset, it doesn't make sense to specify.
The tests set 32-bit with environment variables.
Adding a 32-bit preset is as easy as [including a new configuration with the architecture key](https://docs.microsoft.com/en-us/cpp/build/cmake-presets-vs?view=msvc-170).
Same can be done for compiling for arm
=> CMakePresets: remove reference to 64-bits in name

src/ECS/Archetypes/AbodeArchetype.cpp, src/ECS/Archetypes/TownArchetype.cpp, src/ECS/Archetypes/VillagerArchetype.cpp, src/ECS/Components/Abode.h, src/ECS/Components/Town.h, src/ECS/Components/Villager.h, src/ECS/RegistryContext.h, src/ECS/Systems/TownSystem.cpp, src/ECS/Systems/TownSystem.h, src/Gui/Gui.cpp
These changes assign a villager to their abodes in the same way as vanilla.
Some aspects may be unimplemented due to missing concepts such as Players.
Depends on:
=> Villager abode assign

.github/workflows/copyright-check.yml, .licenserc.json, src/Graphics/ShaderIncluder.h, src/LHScriptX/ScriptingBindingUtils.cpp, src/Serializer/FotFile.cpp
Add an action that checks for our license / copyright comment at the top of each of our project files.
There is a configuration file `.licenserc.json` with the glob path and which is configured to ignore external 3rd party files.
example failed test: https://github.com/openblack/openblack/runs/4755262264?check_suite_focus=true#step:4:150
https://github.com/marketplace/actions/license-checker
=> Add copyright checker

assets/shaders/fs_object.sc, assets/shaders/fs_sky.sc, assets/shaders/fs_terrain.sc, assets/shaders/fs_water.sc, src/3D/Sky.cpp, src/3D/Sky.h, src/Game.cpp, src/Game.h, src/Graphics/ShaderManager.cpp, src/Gui/Gui.cpp, src/Renderer.cpp, src/Renderer.h
Implement the sky texture interpolation as in fragment shader.
Make use of the time of day values for night, dusk and day.
Use that value for terrain brightness
https://user-images.githubusercontent.com/1013356/149610939-baa9642a-b44a-45a5-8433-475994856950.mp4
=> Sky shader

src/ECS/Registry.h
ecs: in 3.9.0, size<C>() is replaced by storage<C>().size()
https://github.com/skypjack/entt/releases/tag/v3.9.0
This fixes the System Deps CI test
=> Update EnTT to 3.9.0

.github/workflows/ci-system-deps.yml
It dawned on me that the system deps are probably compiling single threaded.
On a new system, `MAKEFLAGS` is commented out.
This change to the regex makes sure to uncomment the line if it is commented out.
For reference ubuntu vcpkg config takes 2 minutes 25 seconds to compile
=> CI System Deps: Speed-up compilation

apps/l3dtool/l3dtool.cpp, components/l3d/include/L3DFile.h, components/l3d/src/L3DFile.cpp, src/3D/AxisAlignedBoundingBox.h, src/3D/L3DMesh.cpp, src/3D/L3DMesh.h, src/3D/L3DSubMesh.cpp, src/3D/L3DSubMesh.h, src/ECS/Archetypes/AbodeArchetype.cpp, src/ECS/Archetypes/AnimatedStaticArchetype.cpp, src/ECS/Archetypes/BigForestArchetype.cpp, src/ECS/Archetypes/FeatureArchetype.cpp, src/ECS/Archetypes/MobileObjectArchetype.cpp, src/ECS/Archetypes/MobileStaticArchetype.cpp, src/ECS/Archetypes/TreeArchetype.cpp, src/ECS/Archetypes/Utils.cpp, src/ECS/Archetypes/Utils.h, src/ECS/Archetypes/VillagerArchetype.cpp, src/ECS/Components/Fixed.h, src/ECS/Components/Transform.h, src/ECS/Map.cpp, src/ECS/Map.h, src/ECS/Systems/RenderingSystem.cpp, src/Game.cpp, src/Game.h, src/Gui/MeshViewer.cpp
This matches the acceleration structure used in vanilla to look-up locally close fixed and mobile subclasses.
Vanilla used a linked list for this, this implementation uses a set to avoid duplicates, order should not matter either.
An accelerated look-up is needed to find town congregation point. A different AS could be used such as a BVH (used in modern physics and raytracing), quadtree (more dynamic), kd-tree, etc.
Depends on:
=> Add Map Grid Acceleration Structure

.github/workflows/ci-vcpkg.yml
According to https://github.com/actions/virtual-environments, windows-2022 and windows-latest are now the same
=> Restore windows-2019 tests

.github/workflows/ci-cross-compile.yml, .github/workflows/ci-system-deps.yml, .github/workflows/ci-vcpkg.yml, .github/workflows/clang-format-check.yml
Each build will now provide artifacts in the summary of `VCPKG CI`, `Cross Compile CI` and `System Deps CI`.
We can provide these artifacts to users who don't know how to build, we can use them for tagged releases and we can also use them to quickly test a PR.
There may be a way to combine windows Debug and Release artifacts by giving them the same artifact name which will give an artifact with `Debug/` and `Release/` but that would require too much logic in the yaml file and I didn't do this way.
=> ci: Upload artifacts of builds

assets/shaders/vs_water.sc
OpenGL is unique in the way it orients the y coordinate internally.
Here `texProj` was sampling the reflection framebuffer upside down.
I didn't check Direct3D but I assume the same issue is present and fixed
=> water: Perform y-flip for texProj on non OpenGL platforms

src/CMakeLists.txt
When we moved to static lib, we lost logging to the console for debug builds.
=> logging: Undo regression to logger for debug builds

src/ECS/Archetypes/VillagerArchetype.cpp, src/ECS/Components/WallHug.h, src/ECS/Registry.h, src/ECS/Systems/PathfindingSystem.cpp, src/ECS/Systems/PathfindingSystem.h, src/Enums.h, src/Game.cpp, src/Game.h, src/Gui/Gui.cpp, src/Gui/PathFinding.cpp, src/Gui/PathFinding.h, src/Profiler.h
This PR adds a debug window which lets you select a villager (make sure the green bar intersects them) and a destination and either teleport them, move them using pathfinding or using footpaths.
The actual implementations are not done and will result in warnings in the log. The actual implementation of move to pathfinding is in #338 and walking on footpath is to be done after states (#285) the for it are implemented.
https://user-images.githubusercontent.com/1013356/158035188-cab3714e-53b0-4609-b00f-8f001b6d0b57.mp4
Also adds pause functionality with game paused by default and visible in the bottom right ui.
- WallHug component is in #338
- WallHug component is in #338
Depends on:
=> GUI: Set villager position with window

src/ECS/Archetypes/CameraBookmarkArchetype.cpp, src/ECS/Archetypes/CameraBookmarkArchetype.h, src/ECS/Systems/CameraBookmarkSystem.cpp, src/ECS/Systems/CameraBookmarkSystem.h, src/Game.cpp, src/Game.h, src/Graphics/Texture2D.h, src/Gui/Gui.cpp, src/Gui/TextureViewer.cpp, src/Gui/TextureViewer.h, src/Renderer.cpp, src/Resources/Loaders.cpp, src/Resources/Loaders.h
* Cleaned up our resource loading.
* If loading from a path, use the stem (base name without extension) as the id.
* Add viewer for textures
=> Use Loader API to load all raw textures

src/Game.cpp
Cherry-picking commit to fix master
Fixes  #382
=> Windows uses backwards slash which breaks raw/texture lookup

src/Game.cpp, src/Gui/MeshViewer.cpp, src/Renderer.cpp, src/Renderer.h
Simplify the renderer's call stack by removing mesh and texture resource managers from argument lists.
This actually seems to improve performance and makes the code cleaner.
=> Renderer: Use locator instead of passing managers as args

src/Game.cpp, src/Game.h, src/Gui/Gui.cpp, src/Renderer.cpp, src/Renderer.h
On window resize events, perform a [bgfx::reset](https://bkaradzic.github.io/bgfx/bgfx.html) to reset framebuffers, and reset camera projection.
Fixes #100, #211
=> Reset bgfx and camera projection on window resize

readme.md
This gives a better view of master builds for times like when a build breaks.
It will no longer be polluted by results of failed PRs.
=> Readme: Make badges point to master pushed builds

apps/anmtool/anmtool.cpp, apps/l3dtool/l3dtool.cpp, apps/lndtool/lndtool.cpp, apps/morphtool/morphtool.cpp, apps/packtool/packtool.cpp, components/anm/include/ANMFile.h, components/anm/src/ANMFile.cpp, components/l3d/include/L3DFile.h, components/l3d/src/L3DFile.cpp, components/lnd/include/LNDFile.h, components/lnd/src/LNDFile.cpp, components/morph/include/MorphFile.h, components/morph/src/MorphFile.cpp, components/pack/include/PackFile.h, components/pack/src/PackFile.cpp, src/3D/L3DAnim.cpp, src/3D/L3DMesh.cpp, src/3D/LandIsland.cpp, src/3D/LandIsland.h, src/Game.cpp, src/Parsers/InfoFile.cpp
Fixes #377 
In components:
In apps:
=> Use path instead of string in components and apps

src/Game.h, test/CMakeLists.txt, test/mock/CMakeLists.txt, test/mock/gen_info.py, test/test_load_scene.cpp
Add some unit tests to catch errors in scene file loading. This is useful to build on for more advanced tests like those in #338 
The test revealed some undefined behaviour when trying to get island before one is loaded.
=> Load scene tests

src/LHScriptX/CommandSignature.h, src/LHScriptX/Lexer.cpp, src/LHScriptX/Lexer.h, src/LHScriptX/Script.cpp
Fixes #122, #123
Remove use of new (without delete) in Token creation.
Instead, a plain std::string is present in Token, next to the Union.
Overhead (once during script loading):
- One string copy per command
- One std::string init/deletion per numerical or operator token
=> Memory leaks in LHScriptX::Token::_u and  CommandSignature

.github/workflows/ci-cross-compile.yml, .github/workflows/ci-vcpkg.yml, CMakePresets.json
Implements #410 
Since the configure step using vcpkg builds both `dbg` and `rel`, we're losing a lot of time to rebuilding vcpkg dependencies by doing config in the two types of config builds.
In the case of a cache miss, it can take 15-25 minutes to rebuild the vcpkg dependencies for both Debug and Release builds.
Merging both debug and release into the same build allows us to remove one Config step (15-25 minutes).
It also cuts the number of builds by half which would reduce the load on the caching which probably will result in more cache hits.
Building openblack after configuration takes about 2-4 minutes so in the case of a cache hit, the build takes 2-4 minutes longer. However, there are less builds running per commit, therefore more runners can go simultaneously.
=> actions: Merge config permutations

.github/workflows/ci-cross-compile.yml, .github/workflows/ci-vcpkg.yml
Currently, windows-latest jobs have the same key as the windows-latest x86 cross compile test.
Additionally, all the android build jobs have the same key regardless of architecture.
They aren't the worst conflicts but they do happen. The clang and non-clang ubuntu are the worst case because they create artifacts of the same name but they aren't the same.
Hopefully this will make for more cache hits.
=> ci: Prevent two jobs from having the same cache keys

src/Renderer.cpp
`submitDesc` was getting the address of a stack local const variable for the
identity matrix which becomes invalid when the scope ends.
This causes the `u_model[0]` matrix to be invalid at draw time for all
entities and it is seen in release.
Making the identity matrix static moves the data out of the scope and makes it
long-lived solving the problem.
Fixes #395
=> rendering: Fix invalid data access in entities draw

.github/workflows/ci-cross-compile.yml, .github/workflows/ci-vcpkg.yml, .github/workflows/format-check.yml
`pull_request_target` differs from `pull_request` in that the workflow is taken from the base.
This prevents security issues of forks stealing secrets but means that PRs for workflows can't be tested
It does, however allow PRs to run tests that use secret tokens
=> CI: use pull_request_target for format and vcpkg builds to automatic commenting

.clang-tidy, src/3D/L3DSubMesh.cpp, src/Common/Queue.h, src/ECS/Components/Stream.h, src/Game.cpp, src/Game.h, src/GameWindow.cpp, src/Graphics/FrameBuffer.cpp, src/Graphics/FrameBuffer.h, src/Graphics/ShaderManager.cpp, src/Graphics/ShaderProgram.cpp, src/Graphics/ShaderProgram.h, src/Gui/Console.cpp, src/Serializer/GameThingSerializer.h
I've added the following checks with some exceptions. Some of the exceptions should be removed in follow-up PRs.
* `modernize-use-equals-default`: For modern and easier to read code. We already follow this except for one place
* `performance-*`: To catch unnecessary copies and useless moves.
* `misc-*`: To catch possible code misuse.
=> Additional Clang-tidy checks (simple)

.clang-tidy, apps/anmtool/anmtool.cpp, apps/l3dtool/l3dtool.cpp, apps/lndtool/lndtool.cpp, apps/morphtool/morphtool.cpp, apps/packtool/packtool.cpp, components/l3d/include/L3DFile.h, components/l3d/src/L3DFile.cpp, src/Dynamics/LandBlockBulletMeshInterface.h, src/Enums.h, src/Game.h, src/Graphics/ShaderIncluder.h, src/Gui/Console.cpp, src/Gui/Gui.cpp, src/main.cpp, test/mock/gen_info.cpp
To catch possible bugs due to misuse, uncaught or thrown exceptions.
This change enforces that no exception can bubble up to the main function without being caught.
=> clang-tidy: bugprone-*

.github/workflows/ci-vcpkg.yml, src/CMakeLists.txt
Building with clang tidy checks (`-DOPENBLACK_CLANG_TIDY_CHECKS=ON`) increases build times dramatically.
It some cases it goes from 2 minutes to 20 minutes.
This PR allows the build step to export compilation commands which can be used directly by clang-tidy to gain insight about specific files and how the compile.
A clang-tidy check step has been added using `ZedThree/clang-tidy-review` which downloads compile commands and headers from vcpkg and checks the changed source them after the regular build step has succeeded.
This provides a quicker way to see if a build succeeds which would be of a higher priority than if the style is good.
The job doesn't run in a matrix and takes about 10 minutes on a medium sized change.
The job provides comments in the PRs (see #443).
The job is also smart …
=> Do clang-tidy checks in a dedicated build step

apps/l3dtool/l3dtool.cpp, components/l3d/include/L3DFile.h, src/Debug/MeshViewer.cpp, src/Renderer.cpp, src/Renderer.h
The LOD field was wrong. Firstly, it is at the other end of the dword, second, it is a bitmask for lods 1, 2, 4.
The Status field was offset by one bit and it encodes information about how the object morphs
in the case of building and a graveyard being filled.
Disabled drawing objects that have a status because no status is implemented yet.
Also fixed the meshviewer not showing physics meshes.
TODO:
=> l3d: Fix flags of submesh

apps/l3dtool/l3dtool.cpp, assets/shaders/fs_footprint.sc, assets/shaders/fs_terrain.sc, assets/shaders/vs_footprint_instanced.sc, assets/shaders/vs_terrain.sc, components/l3d/include/L3DFile.h, components/l3d/src/L3DFile.cpp, src/3D/L3DMesh.cpp, src/3D/L3DMesh.h, src/3D/LandBlock.cpp, src/3D/LandBlock.h, src/3D/LandIsland.cpp, src/3D/LandIsland.h, src/Debug/Gui.cpp, src/Debug/LandIsland.cpp, src/Debug/MeshViewer.cpp, src/Debug/MeshViewer.h, src/ECS/Systems/RenderingSystemInterface.h, src/Game.cpp, src/Graphics/FrameBuffer.h, src/Graphics/RenderPass.h, src/Graphics/ShaderManager.cpp, src/Profiler.h, src/Renderer.cpp, src/Renderer.h
=> l3d: Extract footprint mesh and texture

src/ECS/Systems/Implementations/RenderingSystem.cpp, src/ECS/Systems/RenderingSystemInterface.h, src/Renderer.cpp
There is a bug in d3d11 when shutting down bgfx. A failure happens in the driver code and it happens only when `instanceUniformBuffer` is used.
This bug prevents #449 from completing as the game exits non-cleanly.
=> Fix d3d11 release shutdown bug

.github/dependabot.yml
New vcpkg tags come out about every month.
This configuration should have dependabot create a PR to update the vcpkg config monthly. Doing so will run our CI against vcpkg changes and hopefully catch out-of-date packages and vcpkg regressions early.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
=> github: Add dependabot config

.github/workflows/ci-vcpkg.yml, CMakePresets.json, readme.md
Visual studio 2022 works very well and is stable in the test framework.
Remove support for Visual Studio 2019
=> Remove msvc-16 support

assets/shaders/vs_object.sc, assets/shaders/vs_object_hm_instanced.sc, assets/shaders/vs_object_instanced.sc, src/3D/L3DMesh.cpp, src/3D/LandBlock.cpp, src/3D/LandIsland.cpp, src/3D/LandIsland.h, src/3D/Sky.cpp, src/Debug/LandIsland.cpp, src/ECS/Archetypes/AbodeArchetype.cpp, src/ECS/Archetypes/BigForestArchetype.cpp, src/ECS/Archetypes/PotArchetype.cpp, src/ECS/Components/MorphWithTerrain.h, src/ECS/Systems/Implementations/RenderingSystem.cpp, src/ECS/Systems/RenderingSystemInterface.h, src/Enums.h, src/Graphics/ShaderManager.cpp, src/Graphics/Texture2D.cpp, src/Graphics/Texture2D.h, src/Renderer.cpp, src/Renderer.h, src/Resources/Loaders.cpp
This PR adds the functionality to morph objects with the terrain height map.
The objects that do this are documented in https://github.com/openblack/openblack/wiki/3D-Object-Types
Code clean-up and refactor:
* Fixed the Graveyard info.dat enum value
* Added filter type for texture2d in case is it better to point sample height map
* Cleaned-up terrain block mesh generation to be more readable and to expand upon if we decide to merge the meshes into one large one
* The instancing code in Rendering System now uses an unordered map for faster look-ups
I chose not to sample the height map in a shader as this would be a waste of cycles since the height map is static.
Objects are sampled each frame because the meshes are shared and instance drawn.
The attribute for morphing with terrain was …
=> Morph with Terrain

assets/shaders/vs_object.sc
Fixes animated meshes in osx
Closes #541
Before:
After:
=> object: don't asint in metal

src/main.cpp
Direct3D9 doesn't support texture arrays which are required.
Closes #546
=> rendering: Remove Direct3D as an option

assets/shaders/imgui/fs_imgui_image.sc, assets/shaders/imgui/fs_ocornut_imgui.sc, assets/shaders/imgui/varying.def.sc, assets/shaders/imgui/vs_imgui_image.sc, assets/shaders/imgui/vs_ocornut_imgui.sc, src/Debug/Gui.cpp, src/Debug/Gui.h
This fixes imgui on metal on osx
Before:
Encoders with scale 2:
Encoders with scale 1:
=> imgui: Update the draw implementation to use encoders

src/Debug/Gui.cpp, src/Graphics/ShaderManager.cpp
BGFX has support for WSL to use windows d3d. This whitelists d3d macros for BGFX_EMBEDDED_SHADER.
=> linux: Disable d3d from the BGFX_EMBEDDED_SHADER macro.

apps/anmtool/anmtool.cpp, apps/l3dtool/l3dtool.cpp, apps/lndtool/lndtool.cpp, apps/morphtool/morphtool.cpp, apps/packtool/packtool.cpp, test/mock/gen_info.cpp
gcc 12.2.1 complains about missing iostream includes. This is probably due to fstream no longer leaking iostream includes. This could also be due to the new modules feature of c++.
=> Add missing iostream includes

.github/workflows/ci-cross-compile.yml, .github/workflows/ci-vcpkg.yml, src/Debug/Profiler.h
This fixes windows builder defaulting to vcpkg installed with msvc. It also unifies the caches and seems to run much faster.
Ref https://github.com/lukka/run-cmake/issues/113
=> Use pure config of run-vcpkg@11

.github/workflows/ci-cross-compile.yml, .github/workflows/ci-vcpkg.yml
Use `run-vcpkg@v11` for better caching and `run-cmake@main` for fixes to multi step build.
=> CI: Restore annotations for CMake errors/warnings

src/CMakeLists.txt
Bullet dp is compiled using `BT_USE_DOUBLE_PRECISION` which turns floats into doubles. If this is not included in the application, it will attempt to link with non-existent float implementations
=> Bullet: Fix linking with bullet-dp

src/ECS/Systems/Implementations/RenderingSystem.cpp
When preparing transformation of entities for the draw call we currently create a 4x4 identity matrix translate and multiply it by the rotation as a 4x4.
Here we build a 4x4 matrix with the rotation of the transform then translate it by `position x transform` and use a smaller multiplication.
| Debug Master | Debug Fast |
|----------------|----------------|
|![masterDebug](https://github.com/openblack/openblack/assets/83550517/2c324f2a-7eb5-4aed-bc80-50ec898f24db)|![fastermatrix](https://github.com/openblack/openblack/assets/83550517/6cf3dd08-cef4-45ca-a328-1677b1363091)|
| Release Master | Release Fast |
|![releasedMaster](https://github.com/openblack/openblack/assets/83550517/c620e9df-631a-4c9d-9731-11948dfe87a1)|![realeaseFast](https://github.com/openblack/openblack/assets/83550517/bf05 …
=> Faster Transformation matrix for entities

.github/workflows/ci-vcpkg.yml
I noticed that errors to rendering don't show up in the comment and it turns out that `github.sha` refers to the latest common commit.
=> ci: Fix screenshot uploading image of master

.github/workflows/ci-cross-compile.yml, .github/workflows/format-check.yml, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/libsdl/app/SDLActivity.java, android/app/src/main/java/org/openblack/app/FileSystemInterop.java, android/app/src/main/java/org/openblack/app/OpenblackActivity.java, src/3D/LandIsland.cpp, src/3D/Sky.cpp, src/FileSystem/AndroidFileSystem.cpp, src/FileSystem/AndroidFileSystem.h, src/Game.cpp, src/Locator.cpp, src/Parsers/InfoFile.cpp, src/Resources/Loaders.cpp
Fixes and tests building the APK on windows.
Also fixes gradle lint and the apk name
Fixes android failing to find main function
You can now get the openblack apk from the workflow artifacts. E.g. https://github.com/openblack/openblack/suites/6326800004/artifacts/227483860
Implements #402
TODOs:
=> Android: Lint and build APKs

src/3D/TempleInterior.cpp, src/3D/TempleInterior.h
Fixes #642 by moving the camera from the temple position by one on the Y axis so no zero vector appears in calculation.
Fix a bug where the Desactivation of the interior do not lead to the removal of interior entity.
Add a _templeRotation so the camera rotation is set when entering and aligned with the temple.
=> Temple misc fixes

src/3D/Camera.cpp, src/3D/TempleInterior.cpp, src/3D/TempleInterior.h, src/3D/TempleInteriorInterface.h, src/Debug/Temple.cpp, src/ECS/Systems/Implementations/RenderingSystem.cpp, src/ECS/Systems/Implementations/RenderingSystemCommon.cpp, src/ECS/Systems/Implementations/RenderingSystemCommon.h, src/ECS/Systems/Implementations/RenderingSystemTemple.cpp, src/ECS/Systems/Implementations/RenderingSystemTemple.h, src/ECS/Systems/RenderingSystemInterface.h
Try to implement #646, this try to leverage the locator and renderingSystem and switch the rendering system when activating the temple.
The normal rendering system filter out temple interior entity, the temple rendering system filter out all that is not a temple interior entity.
- - [x] This renderer need only to render Interior part currently used by the game.
- - [x] The normal renderer need to not render interior part.
EDIT
Here is an example of the temple without island entities rendered.
Be aware, dynamic loading of the temple not being implemented entering the temple is still not possible on vulkan.
=> Separate the rendering of the Temple

src/Debug/Console.cpp, src/Debug/Console.h, src/Game.cpp, src/LHScriptX/CommandSignature.h, src/LHScriptX/Script.cpp, src/LHScriptX/Script.h, src/LHScriptX/ScriptingBindingUtils.h, test/mobile_wall_hug/test_mobile_wall_hug.cpp, test/test_load_scene.cpp
Implement #617 
The last point will need a further look into how `lhscriptx::ScriptCommandContext` is used as it should be removable but will need a look as to where and it is used in the different part of lhscriptx.
=> Lh script decoupling

src/3D/Camera.cpp, src/ECS/Systems/Implementations/DynamicsSystem.cpp, src/Renderer.cpp
Reversing (1 for the near plane, 0 for the far plane) the Depth value in order to avoid Z-Fighting as observed in #213  (which will be solved by this PR).
Changes the camera perspective matrix and the BGFX state in the renderer.
Superficial check were done on :
- ~Gnm~
- ~Nvn~
- ~Noop~
Example of #213
Same viewpoint now
TBD : Checking that the camera does behave the same and that the math are correct.
=> Reversing the depth

src/Common/ZoomInterpolator.cpp, src/Common/ZoomInterpolator.h, test/CMakeLists.txt, test/test_interpolator.cpp
I was able to reverse engineer the animation used in vanilla black and white.
The curve is a 5d polynomial that tries to approximate a sigmoid function. There are four degrees of freedom when generating a curve: start value (`p0`), end value (`p1`), start slope (`v0`) and end slope (`v1`). Vanilla also stored duration, start current time and current state. None of those are required as the curve is time scale invariant. Any duration can be mapped on a 0 to 1 range. Current state can be tracked by tracking the value `t` in that range.
Duration and current time must be divided into a 0 to 1 range. Velocities must also be scaled by duration to get slopes. Same thing applies to acceleration.
https://www.desmos.com/calculator/zutyj4djtl
=> Reverse engineer animation curve of vanilla

.github/workflows/format-check.yml, android/app/lint.xml
Required for #691 
Upload the report from gradle lint as an artefact in case of failure of the lint check.
As it is a bit hastily/lazily made this PR should be squashed.
=> Ci tests/gradle report upload

src/Common/ZoomInterpolator.cpp, src/Common/ZoomInterpolator.h, test/CMakeLists.txt, test/test_interpolator.cpp
Depends on #697 for support of concepts
I was able to reverse engineer the animation used in vanilla black and white.
The curve is a 5d polynomial that tries to approximate a sigmoid function. There are four degrees of freedom when generating a curve: start value (`p0`), end value (`p1`), start slope (`v0`) and end slope (`v1`). Vanilla also stored duration, start current time and current state. None of those are required as the curve is time scale invariant. Any duration can be mapped on a 0 to 1 range. Current state can be tracked by tracking the value `t` in that range.
Duration and current time must be divided into a 0 to 1 range. Velocities must also be scaled by duration to get slopes. Same thing applies to acceleration.
https://www.desmos.com/calculator/zutyj4djtl
=> Interpolatiors: Add zoom interpolator

.github/workflows/ci-cross-compile.yml, .github/workflows/format-check.yml, android/app/build.gradle
* Clang-format lint is not parsing `requires` correctly
* Gradle lint is failing due to being out of date.
=> Tests: Fix issues with gradle lint and clang-format lint

src/3D/Camera.cpp, src/3D/Camera.h, src/Common/EventManager.h, src/Debug/Gui.cpp, src/Debug/Gui.h, src/Game.cpp, src/Game.h, src/Input/GameActionMap.cpp, src/Input/GameActionMap.h, src/Input/GameActionMapInterface.h, src/Locator.cpp, src/Locator.h
This PR is the first in two or more parts for re-doing the camera controller model.
This bit brings the vanilla input mapping as a service.
The part for rebinding keys is not yet done. This would require a menu, defined Key names and icons and the ability to save and fetch them from the system like vanilla (#293 is close but is using a totally new input mapping strategy).
Vanilla has a total of 64 inputs that can be bound but it also has inputs that can't be rebound such as double clicking. There is also mouse position and delta.
As a proof of concept, I re-worked the current camera to use the input map and no longer use SDL2. The result works as before but the code is far from elegant since it was written with the event callbacks in mind. Since moving the camera up and down and using the …
=> Action map for input

apps/lndtool/lndtool.cpp, components/lnd/include/LNDFile.h, components/lnd/src/LNDFile.cpp, src/3D/LandIsland.cpp, src/Debug/Gui.cpp, src/Game.cpp, src/Game.h, src/LHScriptX/FeatureScriptCommands.cpp, src/LHScriptX/FeatureScriptCommands.h, test/CMakeLists.txt, test/camera/test_set_camera_pos.cpp, test/mock/CMakeLists.txt
Depends on:
The position described in `START_CAMERA_POS` is actually the focus location
that the camera faces.
The origin of the camera is 120 units away and at a latitude of 12.8571 and
longitude of 157.51.
Also moved the game details overlay to a menu option
With these new changes, the comparison screenshots will start looking a lot more like the vanilla versions.
=> Camera: Fix the facing angle at map launch

src/Debug/Gui.cpp, src/Game.cpp
The multitude of submeshes in the citadel reaches bgfx's limit of 4096
vertex buffers.
This is temporary measure until https://github.com/openblack/openblack/issues/727 is solved to allow loading land2.txt
Added the use and limits to the debug ui overlay.
=> citadel: Skip loading LO variants of meshes

src/Camera/Camera.h, src/Camera/CameraModel.h, src/Camera/DefaultWorldCameraModel.cpp, src/Camera/DefaultWorldCameraModel.h, src/ECS/Components/CameraBookmark.h, src/ECS/Registry.h, src/ECS/Systems/CameraBookmarkSystemInterface.h, src/ECS/Systems/Implementations/CameraBookmarkSystem.cpp, src/ECS/Systems/Implementations/CameraBookmarkSystem.h, src/Game.cpp
Exposed functionality to enqueue a fly-to with the camera model.
Added the camera origin to the saved data of a bookmark.
The way bookmarks work is that when you assign one, the hand position sets the position of the bookmark which will act as the camera's focus point. The camera's origin is also saved. Both these are used for fly-to when you restore the bookmark,
The original focus is lost.
Implements #348
Supersedes #356
=> Implement Fly to bookmarks

src/Camera/Camera.cpp, src/Camera/Camera.h, src/Camera/DefaultWorldCameraModel.cpp
Solves a collection of issues found while testing the new camera that didn't warrant locking the PR or weren't found.
In order \:
- There where an invalid access to optional that was not caught during test (In my test i was on release so assert on the * operator were not checked).
- There where strange behavior when clicking on the sky.
- Arcballing ~and flying~ did not work on water.
So i \:
- Changed the check in `UpdateModeFlying` in `DefaultWorldCameraModel.cpp:442` so it check that `_screenSpaceCenterRaycastHit` and removed the check for `_handPosition` as it takes `_screenSpaceCenterRaycastHit` if empty.
- ~In `DeprojectScreenToWorld` at `camera.cpp:142` i used 1 instead of 0 as z value for `rayStartProjectionSpace`, as the depth buffer is reversed due to (#665).~
- I saved both the …
=> Camera issues

.github/workflows/ci-cross-compile.yml, .linelint.yml, android/app/build.gradle, android/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java, android/app/src/main/java/org/libsdl/app/SDLActivity.java, android/app/src/main/res/values/strings.xml
Added signing secrets to the repo which allows us to build and sign release APKs for android. Without signing, it's not possible to install the release apk.
Note: The bad whitespace in java comes from SDL and I'm not going to change it since everything in the `org/libsdl` folder is verbatim the same as the release of SDL.
Note: We will have to update the java source for SDL at every SDL version update.
Closes #632
=> android: Build and sign release APK

src/FileSystem/AndroidFileSystem.cpp
We tried to use the _gamepath as the `storageUriString`. I set the path as the `storageUriString` and find "/".
Solves
- #747
=> Android IsPathValid fix _gamepath used before being set.

components/ScriptLibrary/include/LHVM/LHVM.h, components/anm/include/ANMFile.h, components/l3d/include/L3DFile.h, components/lnd/include/LNDFile.h, components/pack/include/PackFile.h, src/3D/L3DAnim.cpp, src/3D/L3DAnim.h, src/3D/L3DMesh.cpp, src/3D/L3DMesh.h, src/3D/LandIsland.cpp, src/3D/Sky.cpp, src/FileSystem/AndroidFileSystem.cpp, src/FileSystem/AndroidFileSystem.h, src/FileSystem/DefaultFileSystem.cpp, src/FileSystem/DefaultFileSystem.h, src/FileSystem/FileSystemInterface.h, src/Game.cpp, src/Parsers/InfoFile.cpp, src/Resources/Loaders.cpp
The purpose of this PR is to remove the need of checking what type of filesystem to use before reading a file either at compile type (as we have currently to handle android) or at runtime (as proposed in #673).
It divides responsibility as follows \:
- Parsers get data from a stream and build game asset from it.
- The filesystem look for the data and organise it as a istream.
- The stream handles direct access to the data.
As a first draft i moved `void ReadFile(std::istream& stream)` in all parsers from a private to a public method.
Added a `std::unique_ptr<std::istream> GetData(const std::filesystem::path& path)` as the method to ask access to data from the filesystem.
Replaced place where we had to choose between `Open(Locator::filesystem::value().ReadAll(path));` and `Open(path)` with …
=> Unifying the filesystem interface (eg. no more check)

.github/workflows/ci-cross-compile.yml, readme.md
We drop the vcpkg fix for dbus because it is still in draft, we don't control the fix and the fix seems to not be acceptable in the current state by vcpkg devs.
The dbus bug only affects an experimental build so it is acceptable to remove it.
* Closes #769
=> Move vcpkg back to mainline

src/Camera/Camera.cpp, src/Camera/DefaultWorldCameraModel.cpp, src/Game.cpp, test/camera/scenarios/TiltDownZoomOut.h
The conversion function gets the ratio of depth to width of the right triangle that the view frustum traces (`tan(xFov / 2)`, applies the aspect ratio, to turn it to vertical (` / aspect`), turns that back to the angle for the right triangle (`atan`) and back to fov (`x 2`).
Our current implementation converts the angle to fov before applying `atan`.
This causes a bad angle to be fed to the perspective matrix function and it can be seen that something is wrong by resizing the game windows in the horizontal. At a small enough size, the image flips which indicates a negative FOV which shouldn not be possible while the width is positive.
With these changes, we have 1-to-1 correspondence with vanilla.
=> camera: Fix math error in xFov to yFov conversion

apps/anmtool/CMakeLists.txt, apps/glwtool/CMakeLists.txt, apps/l3dtool/CMakeLists.txt, apps/lhvmtool/CMakeLists.txt, apps/lndtool/CMakeLists.txt, apps/morphtool/CMakeLists.txt, apps/packtool/CMakeLists.txt, components/anm/CMakeLists.txt, components/glw/CMakeLists.txt, components/l3d/CMakeLists.txt, components/lnd/CMakeLists.txt, components/morph/CMakeLists.txt, components/pack/CMakeLists.txt, src/CMakeLists.txt
~~In short, first 2 commits refactors boilerplate to functions, what enables 3rd commit: fix for running clang-tidy in msvc environment.~~
~~1st commit is just small fix for `clang-cl` warning I've encountered.~~
clang-tidy get reenabled for msvc for tools and components without any changes.
Only in case of `openblack_lib`, `/EHsc` has to be manually added to `clang-tidy` invocation, see commit description for details.
I've not looked if or how to enable `clang-tidy` for msvc in CI.
Now I can get back to https://github.com/openblack/openblack/pull/789 without having to run full CI for simple linting :)
=> clang-tidy: fix execution for MSVC

.clangd, .gitignore
This adds some basic settings to work with *clangd*.
When generating compile commands for *clangd*, the compiler specifies c++latest, which isn't recognized by clangd (see https://github.com/clangd/clangd/issues/527). A file *.clangd* is provided to force clangd to use c++20.
*Clangd* generates a folder named *.cache* which contains indexing informations. The *.cache* directory is added to *.gitignore*.
=> Basic settings for clangd

assets/shaders/fs_water.sc, assets/shaders/vs_water.sc, src/Graphics/Renderer.cpp
Currently there are several problems with the ocean.
Mainly it just doesn't look like the right colour and there are many reasons for this.
1. In the screenshots, if you happen to have dark theme, the water will look darker because the image has alpha encoded in it.
Dark:
Light
2. The details of vanilla are of different scales and have different orientations as openblack. This can be see if you visualize the UVs.
Vanilla:
Our prior:
3. The "reflection map" was not being used properly. In vanilla, they rendered part of the scene (including the whole bottom hemisphere of the sky) upside how reflected about the horizon into the main render buffer. They simulated a render texture fetch by simply using alpha blending when they drew the water plane. We were misusing `Skya.raw`, the alpha …
=> Fix rendering of the ocean.

.clang-tidy, .clangd, src/3D/Implementations/LandIsland.h, src/3D/Implementations/Ocean.h, src/3D/Implementations/Sky.h, src/3D/Implementations/TempleInterior.h, src/Audio/AudioManager.h, src/Audio/AudioManagerNoOp.h, src/Common/RandomNumberManagerProduction.h, src/Common/RandomNumberManagerTesting.h, src/Debug/Gui.h, src/ECS/MapProduction.h, src/ECS/Systems/Implementations/CameraBookmarkSystem.h, src/ECS/Systems/Implementations/DynamicsSystem.h, src/ECS/Systems/Implementations/HandSystem.h, src/ECS/Systems/Implementations/LivingActionSystem.h, src/ECS/Systems/Implementations/PathfindingSystem.h, src/ECS/Systems/Implementations/PlayerSystem.h, src/ECS/Systems/Implementations/RenderingSystem.h, src/ECS/Systems/Implementations/RenderingSystemCommon.h, src/ECS/Systems/Implementations/RenderingSystemTemple.h, src/ECS/Systems/Implementations/TownSystem.h, src/FileSystem/DefaultFileSystem.h, src/Graphics/Renderer.h, src/Input/GameActionMap.h, src/Resources/Resources.h, src/Windowing/Sdl2WindowingSystem.h
The `LOCATOR_IMPLEMENTATIONS` warnings were converted from warnings to `#pragma message`.
This is a potential risk to future development because the CI treats warnings as errors to prevent the accumulation of valid warnings without preventing local development from being able to see warnings and continue working.
In the case of `LOCATOR_IMPLEMENTATIONS`, it is imperative that the warning is not raised in the upstream branches because it would indicate illegal use of the services implementations instead of the abstract base classses.
=> Revert commits converting `LOCATOR_IMPLEMENTATIONS` warnings to messages
